name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
      - '.github/workflows/phpstan.yml'

permissions:
  contents: read

jobs:
  phpstan:
    uses: laravel-chronicle/.github/.github/workflows/static-analysis.yml@b25037d9e33dfc02530ee0aedb9bf0c675331811 # main
